### ISSUE TITLE
Calculate vascular liver segments based on user input

### ISSUE THREAD

**Issue by gatangen** [ALive-research/Slicer-Liver#116]
Implement processing/extraction of vascular liver segments based on user input from widget #115. 

- [x] Use the logic class from the VMTK module
- [x] Create endpoint lists
- [x] Calculate centerlines from endpoint lists and create MRML nodes
- [x] Create "unique" names for the centerlines, linked to endpoint list. Overwrite previous when recalculating from updated endpoint list
- [x] Remove endpoint markdown after creating centerline

**Comment by olevs** [comment]
- First implementation finished, in PR #110
