### ISSUE TITLE
Create new Slicer Ubuntu 20.04 Docker image

### ISSUE THREAD

**Issue by olevs** [ALive-research/Slicer-Liver#12]
Currently Dockerhub only got one image on aliveresearch: aliveresearch/slicer-build.
This is based on the Centos7 slicer/slicer-base image, and isn't the best solution for the Slicer-Liver project.

I'm not allowed to create new repos for aliveresearch on Dockerhub, that's why we have been using olevs/slicer-build-ubuntu2004.
@RafaelPalomar Can you create aliveresearch/slicer-build-ubuntu2004 in Dockerhub?
I can update the documentation in https://github.com/ALive-research/ALive-Docker, and upload the new Docker image when I'm allowed.

**Comment by RafaelPalomar** [comment]
@olevs, aliveresearch/slicer-build-ubuntu2004 is now created in Dockerhub. I believe you have now permissions to push

**Comment by olevs** [comment]
Docker image aliveresearch/slicer-build-ubuntu2004 is now uploaded
