### ISSUE TITLE
Update Slicer test image

### ISSUE THREAD

**Issue by RafaelPalomar** [ALive-research/Slicer-Liver#123]
Recently, Slicer set C++ 14 or superior. In order to develop code using this standard we should update our test image to a more recent Slicer.

**Comment by olevs** [comment]
I have created and uploaded the new Docker image to both aliveresearch/slicer-build-ubuntu2004 and olevs/slicer-build-ubuntu2004. See pull request #126 for changing to the aliveresearch Docker image on Dockerhub
