### ISSUE TITLE
Getting Slicer-Liver to work on Windows

### ISSUE THREAD

**Issue by olevs** [ALive-research/Slicer-Liver#135]
Current status Windows build issues
All builds are done with the v5.0.2 git tag

* Building Slicer in release mode with Visual Studio Community 2022 don't work. See https://discourse.slicer.org/t/problem-with-slicer-built-in-release-mode-on-windows/23534/2
* Building Slicer in debug mode with Visual Studio Community 2022 seems to work, but an installed VMTK extension won't work (Error: VMTK library is not found)
  * This is the same error I get on Windows when trying to build the VMTK extension myself
* Building Slicer in release mode with Visual Studio Professional 2019 works, after updating VS to the latest version (16.11.15). Not using the latest version cause the release build to fail, at least the 16.8 version I used.
  * Installing the VMTK extension from the extension manager works
  * **Slicer-Liver works in this build configuration!**
  *  Building the VMTK extension still don't work (Error: VMTK library is not found)
     * Probably a configuration issue, but I can't get it to work
* Debug build in VS 2019 works, but gets the same issue with installed VMTK extension not working

**Summary:**
The only option that currently works on Windows is to build in release mode on VS 2019, and installing VMTK from the extension manager. VS 2019 need to be updated to the latest version.

**Comment by RafaelPalomar** [comment]
Thanks @olevs, for the thorough review! It is good that release + VMTK from EM works, that would be the most likely distribuition of the binaries. I suggest that we live with this until we include it in the extension manager. If it fails there, we will have the opportunity to fix things with the help of the Slicer developers.
