### ISSUE TITLE
Slicer vmtk extension broken on macOS

### ISSUE THREAD

**Issue by gatangen** [ALive-research/Slicer-Liver#153]
**Describe the bug**
Slicer-Liver uses the vmtk extension to extract centrelines from the segmented models. When using this functionality, the error "vmtk library not found" is displayed and no centrelines are generated.

**To Reproduce**
1. Build latest SlicerPreview with vmtk extension
2. Build latest Slicer-Liver extension
3. Slicer-Liver - mark points in vessel - press button "Add Vessel Centerline"

**Expected behavior**
A centerline connecting the marked points should be generated.

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 12.3

**Additional context**
May be related to #151

**Comment by gatangen** [comment]
All the automatic tests for SlicerPreview are failing for Slicer vmtk extension on macOS. The test server is also running an old macOS version (10.13).
https://slicer.cdash.org/index.php?project=SlicerPreview&begin=2022-09-12&end=2022-09-21&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=VMTK

**Comment by RafaelPalomar** [comment]
I think this is happening in other systems too. And a solution is on its way: [https://github.com/vmtk/vmtk/pull/438](https://github.com/vmtk/vmtk/pull/438)
