### ISSUE TITLE
Add VMTK crash dataset for testing

### ISSUE THREAD

**Issue by RafaelPalomar** [ALive-research/Slicer-Liver#164]
VMTK can crash in some situations. Here we will add a vessel model to the testing dataset to be able to test this case.

**Comment by RafaelPalomar** [comment]
@dalbenzioG, could you add here a reference to the specific vessels dataset we will use for testing and that we discuss last week?

**Comment by RafaelPalomar** [comment]
@dalbenzioG, never mind. I found it ;)

**Comment by olevs** [comment]
I tried, but couldn't reproduce the error with the added test set (3D-IRCADb-01_08.nrrd)
I also tried deleting the label name, but that didn't create an error.

**Comment by RafaelPalomar** [comment]
This is now in [https://github.com/alive-research/aliveresearchtestingdata/releases/download/SHA256/2e25b8ce2c70cc2e1acd9b3356d0b1291b770274c16fcd0e2a5b69a4587fbf74](https://github.com/alive-research/aliveresearchtestingdata/releases/download/SHA256/2e25b8ce2c70cc2e1acd9b3356d0b1291b770274c16fcd0e2a5b69a4587fbf74)
