### ISSUE TITLE
Add functionality to obtain unconnected group of markups in the same model

### ISSUE THREAD

**Issue by dalbenzioG** [ALive-research/Slicer-Liver#165]

**Comment by olevs** [comment]
The heading is a bit confusing for me, but from our discussion I assume the wanted functionality is:
Add separate centerline segments for the same segment for the same territory ID.

This is possible with the current implementation:
- Add control points and press "Add Vessel Centerline" as normal
- Delete the markup control points before adding the new points. This can be done with the arrow beside the trash bin button.
- Add new control points, and add the new centerline. You may have to press the "Place control point" button, and turn on visibility with the "..." button
- Now two separate centerline segments should be created

**Comment by RafaelPalomar** [comment]
@dalbenzioG, could you check this?

> This is possible with the current implementation:
> 
>     * Add control points and press "Add Vessel Centerline" as normal
> 
>     * Delete the markup control points before adding the new points. This can be done with the arrow beside the trash bin button.
> 
>     * Add new control points, and add the new centerline. You may have to press the "Place control point" button, and turn on visibility with the "..." button
> 
>     * Now two separate centerline segments should be created

**Comment by dalbenzioG** [comment]
> @dalbenzioG, could you check this?
> 
> > This is possible with the current implementation:
> > ```
> > * Add control points and press "Add Vessel Centerline" as normal
> > 
> > * Delete the markup control points before adding the new points. This can be done with the arrow beside the trash bin button.
> > 
> > * Add new control points, and add the new centerline. You may have to press the "Place control point" button, and turn on visibility with the "..." button
> > 
> > * Now two separate centerline segments should be created
> > ```

Yes, sure.

**Comment by olevs** [comment]
I enabled the drop down for adding more point lists. Now it should be possible to keep adding new point lists to make new disconnected centerline segments: https://github.com/ALive-research/Slicer-Liver/pull/170
