### ISSUE TITLE
No names on the segmentation segments causes crash in slicer-liver vessel extraction

### ISSUE THREAD

**Issue by RafaelPalomar** [ALive-research/Slicer-Liver#168]

**Comment by olevs** [comment]
I tried, but couldn't reproduce the error with the added test set (3D-IRCADb-01_08.nrrd)
I also tried deleting the label name, but that didn't create an error.

**Comment by RafaelPalomar** [comment]
I think we should close this one and re-open it if it happens again. Thanks for checking out!
