### ISSUE TITLE
Make Slicer-Liver extension available on stable slicer extension repository

### ISSUE THREAD

**Issue by RafaelPalomar** [ALive-research/Slicer-Liver#177]

**Comment by jamesobutler** [comment]
Slicer Liver is currently available in latest Slicer Stable 5.2.1. It was not available in Slicer 5.0.x, but it has been available in Slicer stable 5.2.x releases.

**Comment by RafaelPalomar** [comment]
@jamesobutler, thanks a lot for having a look at this!
