### ISSUE TITLE
Low Icon Resolution

### ISSUE THREAD

**Issue by rahulpk** [ALive-research/Slicer-Liver#178]
**The icon for SlicerLiver is of low resolution. **

**To Reproduce**
1. Go to 'Install Extensions'
2. Search for 'SlicerLiver'

**Comment by RafaelPalomar** [comment]
Thanks for the feedback. We will look into it

**Comment by RafaelPalomar** [comment]
The image size is probably too small. I have posted a discourse post to
ask about the recommended size and aspect ratio
(https://discourse.slicer.org/t/extension-image-size-aspect-ratio/27206)
