### ISSUE TITLE
Default color values

### ISSUE THREAD

**Issue by RafaelPalomar** [ALive-research/Slicer-Liver#189]
Right now the default color values (and other settings for that matter) are decoupled between the UI (scripted loadable module) and low lever rendering objects (DM's, Mappers, etc.) We should study the possibility to have these values in a logic in such way that the values can be queried from different components. This will  help keeping the settings consistent.

**Comment by RuoyanMeng** [comment]
Is there any default colormap for the Sliver-Liver extension, and default segments color setting? So I can define the Hepatic/Portal contour color accordingly.

**Comment by RafaelPalomar** [comment]
We could use the `GenericAnatomyColors` color table. Related to this is the use of terminologies (and colors associated) for segmentations and derivatives. Here a recent discussion on this:[https://discourse.slicer.org/t/terminologies-questions/27384]( https://discourse.slicer.org/t/terminologies-questions/27384)

**Comment by olevs** [comment]
In LiverSegments we copy an existing Slicer colormap, and call it SlicerLiverColorMap. See: https://github.com/ALive-research/Slicer-Liver/blob/9502786e8f14f6406296166cd36faa974396160d/LiverSegments/LiverSegments.py#L232
If we did it like this we can add our own colors and labels if necessary.

**Comment by RuoyanMeng** [comment]
The colormap used in LiverSegments is Labels, different from the GenericAnatomyColors we used for representing liver structures. I can hardcode the vessel color now and we can discuss which colormap should be used later.
