### ISSUE TITLE
Output of segments separation should be configurable

### ISSUE THREAD

**Issue by RafaelPalomar** [ALive-research/Slicer-Liver#217]
Right now the output of the segments is placed on the same fixed mrml node. For the surgeons it would be interesting to be able to select the output to have (maybe) different segments distributions that can be compared

**Comment by olevs** [comment]
A first simple implementation could be to just create new Vascular territory maps each time we press the button. Then adding a combobox for selecting the one to show.

Is this enough, or do we need to keep all the nodes used to create the territory map as well?
It may be possible to use a parameter node to store some/all of this information, and then replace the nodes in the mrmlScene.
This probably require some work, and we should only consider it if the above simple solution is not good enough for the intended use case.
