### ISSUE TITLE
Explore compilation of module on Windows for redistribuion of packages

### ISSUE THREAD

**Issue by olevs** [ALive-research/Slicer-Liver#223]
- Slicer-Liver no longer compiles on windows. See fix in: #221
- Building the PACKAGE target of Slicer-Liver on Windows seems to give a .zip file that can be used to install Slicer-Liver as an extension.

**Comment by olevs** [comment]
I also managed to create an installer for the VMTK plugin by building the PACKAGE target in the project in the inner-build folder: 
[31282-win-amd64-SlicerVMTK-git9254133-2023-03-20.zip](https://github.com/ALive-research/Slicer-Liver/files/11026897/31282-win-amd64-SlicerVMTK-git9254133-2023-03-20.zip)
We may not need this if we use a released version of Slicer as a basis, but it's good to know that it may be an option if we need it. I have tested these both with my compiled Slicer, and by downloading the latest Slicer release 5.2.2

@gatangen Have tested the same thing on Mac, and it works there as well by running "make package" (or "ninja package") to create the install files

**Comment by RafaelPalomar** [comment]
Great work @olevs!
