### ISSUE TITLE
Python interpreter does not find compiled libraries

### ISSUE THREAD

**Issue by jpdefrutosSINTEF** [ALive-research/Slicer-Liver#30]
**Describe the bug**
When executing Liver.py to build the UI, Python interpreter fails in loading the library qSlicerLiverResectionsModuleWidgetsPythonQt on Windows 10 (Liver.py line 178). The library file it is compiled and exists in the solution directory. Other modules are found and loaded correctly.

**To Reproduce**
Steps to reproduce the behaviour:
1. Configure the project for VS 2019 v16
2. Compile in Debug mode for Windows 10 (x64)
3. Open Slicer, install the Liver extension
4. Open the liver extension, this will execute Liver.py to build the UI an trigger the error.

**Expected behaviour**
To load the qSlicerLiverResectionsModuleWidgetsPythonQt library an complete the execution of Liver.py

**Screenshots**
![python_issue](https://user-images.githubusercontent.com/30429725/150779345-e2ca7544-df38-43f5-805d-e6d05ee79d5c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (version 21H1, build 19043.1415)
 - Version: Slicer 4.13.0, Slicer-liver updated to 27.01.2022

**Additional context**
The libraries are compiled as static (.lib) instead of dynamic (.dll)

**Comment by RafaelPalomar** [comment]
@jpdefrutosSINTEF is this related ([https://discourse.slicer.org/t/python-message-failed-to-import-pythonqt-qslicerxxxxmodulewidgets/21575/3](https://discourse.slicer.org/t/python-message-failed-to-import-pythonqt-qslicerxxxxmodulewidgets/21575/3). If so, please make sure that you reply to that post in discourse to add that we are experiencing similar issues (give me a mention in discourse so I have it referenced and can discuss with the developers tomorrow)

@olevs

**Comment by RafaelPalomar** [comment]
Information needed @olevs, @jpdefrutosSINTEF :

- PYTHONPATH
- LD_LIBRARY_PATH (Linux only)
- Compnent that works on load
- Component that it does not work.

- [ ] Testing another extension @jpdefrutosSINTEF

**Comment by jpdefrutosSINTEF** [comment]
I compiled Slicer with the new Python 3.9, and looks like the bug is gone. The extension is loaded without Python complaining at all, as you can see in blank Python terminal of the attached image.

![image](https://user-images.githubusercontent.com/30429725/153176110-c75506bd-70a5-4da2-8472-531ee9091e2e.png)

**Comment by gatangen** [comment]
Same for me on macOS Javier. A lot of issues in the super build when trying to build Slicer in Debug mode (stops in ITK). Release mode works ok though.

**Comment by jpdefrutosSINTEF** [comment]
Exactly, ITK is the package failing while compiling the debug version... sus

**Comment by RafaelPalomar** [comment]
Could you guys open an issue on the official Slicer repo? I think not having Debug is workable, but you might need it further down the road.

**Comment by jpdefrutosSINTEF** [comment]
Quick update: Slicer compiles fine in Debug mode, as well as Slicer-Liver. Though there is an error when creating the resection plane. I will add the information in another issue, to not glut this thread

**Comment by RafaelPalomar** [comment]
@ALive-research/alive-software Should we close this one?
