### ISSUE TITLE
Adding centerline endpoints don't work correcty

### ISSUE THREAD

**Issue by olevs** [ALive-research/Slicer-Liver#32]
**Describe the bug**
When trying to add endpoints for the centerline calculation the user interface don't allow setting points in all parts of the selected structure. The issue seems to be that vtkOctreePointLocator::FindClosestPoint that is being used to find the closest point on the structure don't really provide the closest point to most of the structure.

**To Reproduce**
1. Select the Liver module
2. Press "Reload and Test" 
3. Choose LiverSegmentation000
4. Select "hepatic" as "Reference Model"
5. Press "Add segment" and try to select points on the vessels
6. Now the white marker only show up for small parts of the vessels, and not for the whole structure

**Expected behavior**
I expect the white marker to show everywhere on the selected structure

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04

**Additional context**
Printing out the self.__distance shows that the distances gotten from vtkOctreePointLocator::FindClosestPoint are incorrect, suggesting that this function don't work for this model.

**Comment by RafaelPalomar** [comment]
This behavior seems to be more exacerbated in some systems than others (in my two computers it works flawlessly, for @egipane it did not work all that good and in some other systems it does not work at all). I think we should replace the locator by the regular placement of markups points for the time being (similar to SliceExtension-VMTK). 

What do you think, @olevs?

**Comment by olevs** [comment]
Yes, using the regular markups placement functionality is an option. It seems that Slicer got it's own function for finding the closest points: vtkSlicerMarkupsWidgetRepresentation::FindClosestPointOnWidget. Perhaps we can replace vtkOctreePointLocator::FindClosestPoint with this function to get the existing code working

**Comment by RafaelPalomar** [comment]
Yes, we can try. I remember digging quite deep on the locator because other locators had very bad performance. But that's been a while ago.

**Comment by RafaelPalomar** [comment]
This is not relevant as the VMTK UI approach is going to be used
