### ISSUE TITLE
Create the "Liver Analysis" `qt-scripted-module`

### ISSUE THREAD

**Issue by RafaelPalomar** [ALive-research/Slicer-Liver#4]

**Comment by RafaelPalomar** [comment]
@olevs I've been thinking in the layout that you, @jpdefrutosSINTEF and @gatangen came up with: Unified UI in the `Slice-Liver` module, instead of separate ui modules. If we follow that path, this issue needs to be superseded. I've opened a thread in discourse ([https://discourse.slicer.org/t/slicer-qt-loadable-modules-as-libraries-to-support-other-modules/21594](https://discourse.slicer.org/t/slicer-qt-loadable-modules-as-libraries-to-support-other-modules/21594). 

What's your opinion?

**Comment by olevs** [comment]
I guess it depends on what is possible with Slicer, and how easy it is to work with. As long as we got a limited number of features a GUI combining all makes sense, but when the number increase we may have to split them into more modules, or create separate modules for specific "procedures".

**Comment by RafaelPalomar** [comment]
This is obsolete
