### ISSUE TITLE
Failed to create node of type vtkMRMLLiverResectionNode

### ISSUE THREAD

**Issue by jpdefrutosSINTEF** [ALive-research/Slicer-Liver#98]
**Describe the bug**
On debug mode, when creating a new resection, the error following debug error is prompted:
`ASSERT failure in createNode: "Failed to create node of type [vtkMRMLLiverResectionNode]", file C:\S\Slicer\Libs\MRML\Widgets\qMRMLNodeFactory.cxx, line 74
`

On release mode, the resection plane is not created, and no error message is prompted.

**To Reproduce**
1. Run Slicer (updated to the latest commit in the master branch) on Debug mode and on Windows 10
2. Proceed as usual (create the label maps, distance map and models)
3. Create a new resection

**Expected behavior**
A new resection plane should be created

On release mode, an error or warning should be prompted.

**Screenshots**
![image](https://user-images.githubusercontent.com/30429725/153366951-32b2d30b-5b49-4a45-905f-86737441579d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 21H1 (build 19043.1466)

**Additional context**

**Comment by jpdefrutosSINTEF** [comment]
No updates so far, perhaps that I managed to compile both Slicer and the extension (had to wipe clean everything and start ober). But the error is still there. I tried debugging both Slicer and the extension, but with little success.

I used LiClipse for the UI Python code. Tried to capture when the MRMLLiverResectionNode object is created (when selection "Create new node") in the Resection ComboBox, but the error seems to be triggered somewhere else than "onResectionNodeChanged()" function.
Used VisualStudio to debug Slicer and the extension (followed the docs for this one: https://slicer.readthedocs.io/en/latest/developer_guide/debugging/windowscpp.html). None of the extension objects get loaded on VisualStudio debugger, so I can't track where in the extension the MRML node gets created. I could capture when the CreateNodeByClass function in the Slicer app (qMRMLNodeFactory L:74) is called. And this is the furthest I got.

**Comment by jpdefrutosSINTEF** [comment]
I opened an issue on the Slicer forum. Link: https://discourse.slicer.org/t/mrml-none-not-found/23067

**Comment by jpdefrutosSINTEF** [comment]
Some bittersweet news: the extension can be compiled and run on Windows, as proven by Andras Lasso (https://discourse.slicer.org/t/mrml-none-not-found/23067/6).
Yet I still get the error. But at least we now know that the problem is on my computer.

**Comment by olevs** [comment]
I have made a summary of the results of the different Slicer build tries: https://github.com/ALive-research/Slicer-Liver/issues/135
The conclusion is that only the latest version of VS 2019 works, the build have to be release, and the VMTK extension have to be installed from the extension manager, not built.
